modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "stay_frosty"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "AuroraAster"
displayURL = "https://modrinth.com/mod/stay-frosty"
displayName = "Stay Frosty"
description = '''
    Cold mobs make ya cold now. Who woulda thunk it
    '''

[[dependencies.stay_frosty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stay_frosty]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"